export const ADD_PIECE_STAR_1 = 'ADD_PIECE_1';
export const REMOVE_PIECE_STAR_1 = 'REMOVE_PIECE_1';
export const ADD_PIECE_STAR_2 = 'ADD_PIECE_2';
export const REMOVE_PIECE_STAR_2 = 'REMOVE_PIECE_2';
export const ADD_PIECE_STAR_3 = 'ADD_PIECE_3';
export const REMOVE_PIECE_STAR_3 = 'REMOVE_PIECE_3';

export default {
  ADD_PIECE_STAR_1,
  REMOVE_PIECE_STAR_1,
  ADD_PIECE_STAR_2,
  REMOVE_PIECE_STAR_2,
  ADD_PIECE_STAR_3,
  REMOVE_PIECE_STAR_3,
};
